### ISSUE TITLE
mkl-stacks "import error" of torch and tensorflow

### ISSUE THREAD

**Issue by Balasubra** [intel/stacks#22]
Dear Intel team,
I tested latest mkl based stacks for pytorch and tensorflow on a system running with CentOS-7 and x86-64 architecture. While the pulling of the container went fine, attempt to import pytorch or tensorflow resulted in import error as follows

"import failure : Illegal instruction (core dumped)” error. However, I noted that import of other python modules (eg. numpy) was successful.

Could you help me to resolve the issue,
Bala

**Comment by unrahul** [comment]
That is because the stack is designed to work on  skylake-x and above (avx512 instructions) and the system you are trying on might not have avx512. You can verify if your system has avx512 using 

`lscpu | grep  'avx512' `
