### ISSUE TITLE
caffe2 with avx support

### ISSUE THREAD

**Issue by Balasubra** [intel/stacks#23]
The following query if more of a request than an issue.
I pulled the clearlinux/stacks-pytorch-oss stack and tested AlexNet benchmarks as suggested here (https://docs.01.org/clearlinux/latest/guides/stacks/dlrs.html) with caffe2 obtained from the following repository 
https://github.com/pytorch/pytorch.git
I noted the following message while running the benchmark “CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU”.
I would like to know if caffe2 with avx support could be placed within your clearlinux containers for pytorch.

Thanks,
Bala

**Comment by unrahul** [comment]
caffe2 utilizes avx through MKLDNN in this build, and thus will utilize available vector instructions on your architecture. Please make sure that your system has avx512 instructions as well..as the stack is designed to run on such systems.
