### ISSUE TITLE
Code to transform docker to singularity container d2s.py  works with python 3.6 but not in python 3.4

### ISSUE THREAD

**Issue by smarocchi** [intel/stacks#33]
Hello, 
         I tried to use your code d2s.py. It works properly and recognize both the installation of docker and singularity in my VM to produce a singularity image file. I noticed however some issues that I want to refer you:
    
    1) The code works with python 3.6 but not with python 3.4.

    2) The transformation from docker to singularity do not pass the correct environment variables to the final container.

I spoke with your colleague  Unnikrishnan Nair, Rahul and he suggested to send you this comments.

Thanks

**Comment by Meadosc** [comment]
Hi @alchemroz, thanks for the feedback. We'd like some more information.

1) How does the script fail in python 3.4? Can you provide the code and stack trace?

2) What environment variables are not passed? Can you provide the code?

**Comment by smarocchi** [comment]
Sure, 
          among the others tests I tried to transform clearlinux/stacks-horovod-pytorch-cpu-mkl:v0.5.0

1) When I tried to use python3.4 I get the following error, but once again with python3.6 the same command worked properly

[centos@marocchi-dev sing_clear_linux_intel]$ python3.4 d2s.py --convert_docker_images 0 1 
checking if singularity is installed
Traceback (most recent call last):
  File "d2s.py", line 97, in <module>
    check_singularity_version()
  File "d2s.py", line 62, in check_singularity_version
    s_ver = subprocess.run(["singularity", "version"])
  File "/home/centos/.local/lib/python3.4/site-packages/run/__init__.py", line 145, in __new__
    process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
  File "/home/centos/.local/lib/python3.4/site-packages/run/__init__.py", line 121, in create_process
    shlex.split(command),
  File "/usr/lib64/python3.4/shlex.py", line 276, in split
    return list(lex)
  File "/usr/lib64/python3.4/shlex.py", line 266, in __next__
    token = self.get_token()
  File "/usr/lib64/python3.4/shlex.py", line 93, in get_token
    raw = self.read_token()
  File "/usr/lib64/python3.4/shlex.py", line 121, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'list' object has no attribute 'read'


2) All the environment variables are lost in the process, in particular the following the I import everytime I have to use the container with singularity:

SINGULARITYENV_INTRA_OP_PARALLELISM_THREADS=24 \
SINGULARITYENV_MPI_LIBS=/usr/lib64/libmpi.so \
SINGULARITYENV_LA_INCLUDE=/usr/include \
SINGULARITYENV_XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg \
SINGULARITYENV_GTK_IM_MODULE=ibus \
SINGULARITYENV_MPI_CC=/usr/bin/mpicc \
SINGULARITYENV_MPI_VERSION=3.2 \
SINGULARITYENV_EDITOR=/usr/bin/nano \
SINGULARITYENV_PWD=/workspace \
SINGULARITYENV_INTER_OP_PARALLELISM_THREADS=2 \
SINGULARITYENV_CXX=g++ \
SINGULARITYENV_MPI_INCLUDE=/usr/include/ \
SINGULARITYENV_LA_LIBS=/usr/lib64/libopenblas.so.0 \
SINGULARITYENV_TZ=UTC \
SINGULARITYENV_MPI_PATH=/usr/lib64/ \
SINGULARITYENV_HOME=/ \
SINGULARITYENV_LANG=en_US.UTF-8 \
SINGULARITYENV_MESA_GLSL_CACHE_DISABLE=0 \
SINGULARITYENV_TERM=xterm \
SINGULARITYENV_PYTHONIOENCODING=utf-8:surrogateescape \
SINGULARITYENV_AR=gcc-ar \
SINGULARITYENV_SHLVL=0 \
SINGULARITYENV_NM=gcc-nm \
SINGULARITYENV_LA_PATH=/usr/lib64/ \
SINGULARITYENV_LD_LIBRARY_PATH=/usr/lib64:/opt/conda/lib \
SINGULARITYENV_KMP_AFFINITY=verbose,granularity=thread,compact,1,0 \
SINGULARITYENV_KMP_BLOCKTIME=1 \
SINGULARITYENV_KMP_SETTINGS=1 \
SINGULARITYENV_OMP_NUM_THREADS=24 \
SINGULARITYENV_PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
SINGULARITYENV_CC=gcc \
SINGULARITYENV_LA_VERSION=OpenBLAS \
SINGULARITYENV_I_MPI_DEBUG="3" \
SINGULARITYENV_I_MPI_DEBUG_OUTPUT=debug.dbg \

**Comment by unrahul** [comment]
@alchemroz thank you for the steps to recreate the issue, we shall debug this and see what can be done.

**Comment by unrahul** [comment]
Official supported version moved to Python 3.6 and the package will not install on lower versions of Python, closing the issue.
