### ISSUE TITLE
Any Chance for Intel oneAPI?

### ISSUE THREAD

**Issue by mathomp4** [intel/stacks#92]
I just discovered stacks and thought it might solve some issues for me. Namely, I'd like a Docker image where I can run Intel Fortran. I did try building my own using the [Intel Apt instructions](https://software.intel.com/content/www/us/en/develop/articles/installing-intel-oneapi-toolkits-via-apt.html) and, well, I ended up with a 21 GB image. Obviously, I don't know what I'm doing in re Docker, so I thought maybe Stacks might be able to use it soon?

I did try pulling the sysstacks/hpcrs-centos:latest image but:
```console
[root@f06e452db89e workspace]# ifort

Error: A license for Comp-FL could not be obtained.  (-1,359,2).

Is your license file in the right location and readable?
The location of your license file should be specified via
the $INTEL_LICENSE_FILE environment variable.
...
```
The nice thing with oneAPI is it's free-ness :)

**Comment by unrahul** [comment]
We are planning this to be included in our next release in few weeks

**Comment by unrahul** [comment]
We have updated our HPCRS stacks with one API component, the latest v0.3.0 release has the components, kindly try it out and let us know if you have any feedback..
